### PR TITLE
lint, tests, browser tests, readme update

### PR DESCRIPTION
**Pull request by diasdavid**
bump minor :)

### CODE REVIEW

**Comment by jbenet** [comment]
@diasdavid thanks! published (btw you have owner on this)

**Comment by diasdavid** [comment]
Thank you :) I can't merge though https://github.com/jbenet/js-multiaddr/pull/5

**Comment by diasdavid** [comment]
btw, **protip:** use [`npm-release`](https://www.npmjs.com/package/npm-release) like `npm release patch`, so that it creates a release with a tag and so on. @richardlitt, you might want to add this to the JS boilarplate for our modules :)

**Comment by diasdavid** [comment]
@jbenet just noticed that I also don't have npm publish priv (was in a middle of a release and failed)

https://www.npmjs.com/package/multiaddr

**Comment by jbenet** [comment]
try now?

**Comment by diasdavid** [comment]
sweet, done :)

**Pull request merged**
